[package]
name = "token_wallet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
ic-cdk = "0.7.0"
ic-cdk-macros = "0.6.0"
serde = "1.0.152"
ic-types = "0.7.0"